services:
  - type: web
    name: myproject
    env: python
    plan: free
    repo: https://github.com/neeteesh234/django-render
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: myproject-db
          property: connectionString
databases:
  - name: myproject-db
    plan: free